Repository fieldsight/fieldsight-mobile, pull requests merged in 2019-08, with the labels that each got.

#332 [#331]adds support for multiple languages (question) in previous submission details screen
  collect_app/src/main/java/org/bcss/collect/naxa/generalforms/data/GetResponce.java
  collect_app/src/main/java/org/bcss/collect/naxa/submissions/MultiViewAdapter.java
  collect_app/src/main/java/org/bcss/collect/naxa/submissions/PreviousSubmissionDetailActivity.java
  collect_app/src/main/java/org/bcss/collect/naxa/submissions/PreviousSubmissionListActivity.java
  collect_app/src/main/res/layouts/fieldsight/layout/activity_form_history_detail.xml
Labels: bug

#334 Unused files removed
  collect_app/src/main/java/org/fieldsight/naxa/EmptyViewHolder.java
  collect_app/src/main/java/org/fieldsight/naxa/common/CallbackWrapper.java
  collect_app/src/main/java/org/fieldsight/naxa/common/FieldSightDownloadFormListUtils.java
  collect_app/src/main/java/org/fieldsight/naxa/common/ImageUtils.java
  collect_app/src/main/java/org/fieldsight/naxa/common/LinearLayoutManagerWrapper.java
  collect_app/src/main/java/org/fieldsight/naxa/common/MyAppGlideModule.java
  collect_app/src/main/java/org/fieldsight/naxa/common/RVEmptyObserver.java
  collect_app/src/main/java/org/fieldsight/naxa/common/Report.java
  collect_app/src/main/java/org/fieldsight/naxa/common/ScrollAwareFABBehavior.java
  collect_app/src/main/java/org/fieldsight/naxa/common/ScrollBehavior.java
  collect_app/src/main/java/org/fieldsight/naxa/common/SnackBarBehaviour.java
  collect_app/src/main/java/org/fieldsight/naxa/common/Truss.java
  collect_app/src/main/java/org/fieldsight/naxa/common/User.java
  collect_app/src/main/java/org/fieldsight/naxa/common/ViewUtils.java
  collect_app/src/main/java/org/fieldsight/naxa/common/anim/ScaleUpAndDownItemAnimator.java
  collect_app/src/main/java/org/fieldsight/naxa/common/database/ProjectFilterLocalSource.java
  collect_app/src/main/java/org/fieldsight/naxa/common/database/SiteOverideRepository.java
  collect_app/src/main/java/org/fieldsight/naxa/common/utilities/SnackbarHelper.java
  collect_app/src/main/java/org/fieldsight/naxa/demo/RawAssetLoader.java
  collect_app/src/main/java/org/fieldsight/naxa/educational/EducationalMaterialsRepository.java
  collect_app/src/main/java/org/fieldsight/naxa/educational/EducationalMaterialsViewHolder.java
  collect_app/src/main/java/org/fieldsight/naxa/generalforms/GeneralFormsFragBinding.java
  collect_app/src/main/java/org/fieldsight/naxa/generalforms/SyncCommentLifecycleObserver.java
  collect_app/src/main/java/org/fieldsight/naxa/network/ProjectResponse.java
  collect_app/src/main/java/org/fieldsight/naxa/notificationslist/FieldSightNotificationsDiffCallback.java
  collect_app/src/main/java/org/fieldsight/naxa/notificationslist/NotificationRemoteSource.java
  collect_app/src/main/java/org/fieldsight/naxa/onboarding/DownloadingStatus.java
  collect_app/src/main/java/org/fieldsight/naxa/profile/UserActivity.java
  collect_app/src/main/java/org/fieldsight/naxa/project/ProjectModel.java
  collect_app/src/main/java/org/fieldsight/naxa/project/ProjectModelImpl.java
  collect_app/src/main/java/org/fieldsight/naxa/project/ProjectPresenter.java
  collect_app/src/main/java/org/fieldsight/naxa/project/ProjectPresenterImpl.java
  collect_app/src/main/java/org/fieldsight/naxa/project/ProjectView.java
  collect_app/src/main/java/org/fieldsight/naxa/site/CreateSiteDetailFormStatus.java
  collect_app/src/main/java/org/fieldsight/naxa/site/RandomObjectFiller.java
  collect_app/src/main/java/org/fieldsight/naxa/site/SiteClusterLocalSource.java
  collect_app/src/main/java/org/fieldsight/naxa/site/SiteDetailActivity.java
  collect_app/src/main/java/org/fieldsight/naxa/sitedocuments/SiteDocumentsAdapter.java
  collect_app/src/main/java/org/fieldsight/naxa/stages/data/StageBuilder.java
  collect_app/src/main/java/org/fieldsight/naxa/stages/data/SubstageBuilder.java
Labels: enhancement

#336 [#335] show server not found message instead for unknown host exception
  collect_app/src/main/java/org/fieldsight/naxa/common/rx/RetrofitException.java
  collect_app/src/main/java/org/fieldsight/naxa/common/rx/RxErrorHandlingCallAdapterFactory.java
  collect_app/src/main/java/org/fieldsight/naxa/login/LoginModelImpl.java
  collect_app/src/main/java/org/fieldsight/naxa/submissions/PreviousSubmissionDetailActivity.java
  collect_app/src/main/java/org/odk/collect/android/utilities/DateTimeUtils.java
Labels: enhancement

#341 zero division issue fixe
  collect_app/src/main/java/org/fieldsight/naxa/v3/adapter/SyncAdapterv3.java
Labels: priority, urgent

#339 338/create intermediary files
  collect_app/src/androidTest/java/org/odk/collect/android/dao/InstancesDaoTest.java
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/fieldsight/naxa/FSInstanceUploaderListActivity.java
  collect_app/src/main/java/org/fieldsight/naxa/FsInstanceChooserList.java
  collect_app/src/main/java/org/fieldsight/naxa/common/FieldSightFormListFragment.java
  collect_app/src/main/java/org/fieldsight/naxa/common/FieldSightUserSession.java
  collect_app/src/main/java/org/fieldsight/naxa/flagform/FlagFormRemoteSource.java
  collect_app/src/main/java/org/fieldsight/naxa/flagform/FlaggedInstanceActivity.java
  collect_app/src/main/java/org/fieldsight/naxa/flagform/InstanceRemoteSource.java
  collect_app/src/main/java/org/fieldsight/naxa/forms/FieldSightInstanceDAO.java
  collect_app/src/main/java/org/fieldsight/naxa/fragments/FSDataManagerList.java
  collect_app/src/main/java/org/fieldsight/naxa/generalforms/GeneralFormsFragment.java
  collect_app/src/main/java/org/fieldsight/naxa/helpers/FSInstancesDao.java
  collect_app/src/main/java/org/fieldsight/naxa/migrate/MigrateFieldSightViewModel.java
  collect_app/src/main/java/org/fieldsight/naxa/site/ProjectDashboardActivity.java
  collect_app/src/main/java/org/fieldsight/naxa/site/SiteDashboardFragment.java
  collect_app/src/main/java/org/fieldsight/naxa/site/db/SiteRemoteSource.java
  collect_app/src/main/java/org/fieldsight/naxa/survey/SurveyFormsActivity.java
  collect_app/src/main/java/org/odk/collect/android/activities/FileManagerTabs.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceChooserList.java
  collect_app/src/main/java/org/odk/collect/android/activities/InstanceUploaderListActivity.java
  collect_app/src/main/java/org/odk/collect/android/dao/InstancesDao.java
  collect_app/src/main/java/org/odk/collect/android/fragments/DataManagerList.java
  collect_app/src/test/java/org/odk/collect/android/activities/InstanceUploaderListActivityTest.java
Labels: code quality, enhancement

#343 Queue and downloads forms one project at a time (#342)
  collect_app/build.gradle
  collect_app/internal/output.json
  collect_app/release/output.json
  collect_app/src/main/java/org/fieldsight/naxa/common/Constant.java
  collect_app/src/main/java/org/fieldsight/naxa/common/ODKFormRemoteSource.java
  collect_app/src/main/java/org/fieldsight/naxa/common/exception/FormDownloadFailedException.java
  collect_app/src/main/java/org/fieldsight/naxa/v3/adapter/SyncViewHolder.java
  collect_app/src/main/java/org/fieldsight/naxa/v3/network/SyncLocalSourcev3.java
  collect_app/src/main/java/org/fieldsight/naxa/v3/network/SyncServiceV3.java
  collect_app/src/main/java/org/odk/collect/android/logic/FormDetails.java
Labels: enhancement

#356 Replaced application context with view context on map marked tap acti…
  collect_app/src/main/java/org/fieldsight/naxa/site/FragmentHostActivity.java
  collect_app/src/main/java/org/fieldsight/naxa/site/SiteInfoWindow.java
Labels: bug

#354 Only select sites that don't have a parent site (#353)
  collect_app/src/main/java/org/fieldsight/naxa/site/db/SiteDao.java
Labels: bug
