Repository fieldsight/fieldsight-mobile, pull requests merged in 2019-06, with the labels that each got.

#194 [#189] fixed typo on calling strings, for logout message
  collect_app/src/main/java/org/bcss/collect/naxa/common/FieldSightUserSession.java
Labels: bug

#193 [#191] changed site list relative layout to linear
  collect_app/src/main/res/layouts/fieldsight/layout/site_list_item.xml
Labels: bug

#197 196/feature site documents load online and cache
  collect_app/src/main/java/org/bcss/collect/naxa/common/TouchImageView.java
  collect_app/src/main/java/org/bcss/collect/naxa/common/ViewUtils.java
  collect_app/src/main/java/org/bcss/collect/naxa/network/APIEndpoint.java
  collect_app/src/main/java/org/bcss/collect/naxa/network/ApiInterface.java
  collect_app/src/main/java/org/bcss/collect/naxa/network/ServiceGenerator.java
  collect_app/src/main/java/org/bcss/collect/naxa/sitedocuments/ImageViewerActivity.java
  collect_app/src/main/java/org/bcss/collect/naxa/sitedocuments/SiteDocumentsListActivity.java
  collect_app/src/main/java/org/bcss/collect/naxa/v3/network/ApiV3Interface.java
  collect_app/src/main/res/layouts/fieldsight/layout/activity_image_viewer.xml
  collect_app/src/main/res/layouts/fieldsight/layout/activity_site_documents_list.xml
  collect_app/src/main/res/layouts/fieldsight/layout/content_image_viewer.xml
  collect_app/src/main/res/layouts/fieldsight/layout/progress_layout.xml
  collect_app/src/main/res/layouts/fieldsight/values/styles.xml
Labels: bug, enhancement

#201 [#190] site types are loaded from project table, in filter dialog
  collect_app/src/main/java/org/bcss/collect/naxa/network/APIEndpoint.java
  collect_app/src/main/java/org/bcss/collect/naxa/project/data/ProjectRepository.java
  collect_app/src/main/java/org/bcss/collect/naxa/site/CreateSiteActivity.java
  collect_app/src/main/java/org/bcss/collect/naxa/site/CreateSiteViewModel.java
  collect_app/src/main/java/org/bcss/collect/naxa/site/SiteClusterSpinnerAdapter.java
  collect_app/src/main/java/org/bcss/collect/naxa/site/SiteListFragment.java
  collect_app/src/main/java/org/bcss/collect/naxa/site/SiteTypeSpinnerAdapter.java
  collect_app/src/main/java/org/bcss/collect/naxa/v3/network/Region.java
Labels: bug, enhancement

#213 [#212] return empty error instead of passing null for gson conversion
  collect_app/src/main/java/org/bcss/collect/naxa/network/APIEndpoint.java
  collect_app/src/main/java/org/bcss/collect/naxa/project/data/ProjectRepository.java
Labels: bug

#228 [#222] uses fileprovider to get uri
  collect_app/src/main/java/org/bcss/collect/naxa/BackupActivity.java
Labels: bug

#234 233 report page
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/bcss/collect/naxa/network/APIEndpoint.java
  collect_app/src/main/java/org/bcss/collect/naxa/network/ApiInterface.java
  collect_app/src/main/java/org/bcss/collect/naxa/project/ProjectListActivity.java
  collect_app/src/main/java/org/bcss/collect/naxa/report/ReportActivity.java
  collect_app/src/main/res/layouts/fieldsight/layout/activity_report.xml
  collect_app/src/main/res/layouts/fieldsight/menu/main_menu_fieldsight.xml
  collect_app/src/main/res/layouts/fieldsight/values/strings.xml
Labels: code quality, enhancement, feature request

#247 185/bugfix general form not showing
  collect_app/internal/output.json
  collect_app/src/main/java/org/bcss/collect/naxa/common/database/BaseDaoFieldSight.java
  collect_app/src/main/java/org/bcss/collect/naxa/generalforms/GeneralFormViewModel.java
  collect_app/src/main/java/org/bcss/collect/naxa/generalforms/data/GeneralFormDAO.java
  collect_app/src/main/java/org/bcss/collect/naxa/generalforms/data/GeneralFormLocalSource.java
  collect_app/src/main/java/org/bcss/collect/naxa/generalforms/data/GeneralFormRepository.java
  collect_app/src/main/java/org/bcss/collect/naxa/scheduled/data/ScheduledFormDAO.java
  collect_app/src/main/java/org/bcss/collect/naxa/stages/data/StageFormDAO.java
  collect_app/src/main/java/org/bcss/collect/naxa/stages/data/StageLocalSource.java
  collect_app/src/main/java/org/bcss/collect/naxa/stages/data/StageRemoteSource.java
  collect_app/src/main/java/org/bcss/collect/naxa/substages/data/SubStageDAO.java
  collect_app/src/main/java/org/bcss/collect/naxa/substages/data/SubStageLocalSource.java
Labels: bug

#251 248/bugfix formsdownload failing
  collect_app/src/main/java/org/bcss/collect/naxa/common/ODKFormRemoteSource.java
  collect_app/src/main/java/org/odk/collect/android/utilities/FormDownloader.java
Labels: bug
