Repository fieldsight/fieldsight-mobile, pull requests merged in 2019-05, with the labels that each got.

#127 WIP: 126 google signin
  collect_app/src/main/AndroidManifest.xml
  collect_app/src/main/java/org/bcss/collect/naxa/login/BaseLoginActivity.java
  collect_app/src/main/java/org/bcss/collect/naxa/login/LoginActivity.java
  collect_app/src/main/java/org/bcss/collect/naxa/login/LoginModel.java
  collect_app/src/main/java/org/bcss/collect/naxa/login/LoginModelImpl.java
  collect_app/src/main/java/org/bcss/collect/naxa/login/LoginPresenter.java
  collect_app/src/main/java/org/bcss/collect/naxa/login/LoginPresenterImpl.java
  collect_app/src/main/java/org/bcss/collect/naxa/network/APIEndpoint.java
  collect_app/src/main/java/org/bcss/collect/naxa/network/ApiInterface.java
  collect_app/src/main/java/org/bcss/collect/naxa/notificationslist/FlaggedInstanceActivity.java
  collect_app/src/main/res/layouts/odk/layout/activity_login.xml
  collect_app/src/main/res/raw/client_secret.json
Labels: enhancement

#139 [#134] updated db to 9
  collect_app/src/main/java/org/bcss/collect/naxa/common/database/FieldSightConfigDatabase.java
Labels: bug

#143 [#142] removes prev sub from sync
  collect_app/schemas/org.bcss.collect.naxa.common.database.FieldSightConfigDatabase/10.json
  collect_app/schemas/org.bcss.collect.naxa.common.database.FieldSightConfigDatabase/9.json
  collect_app/src/main/java/org/bcss/collect/naxa/common/database/FieldSightConfigDatabase.java
  collect_app/src/main/java/org/bcss/collect/naxa/sync/ContentDownloadActivity.java
  collect_app/src/main/java/org/bcss/collect/naxa/sync/DownloadViewModel.java
  collect_app/src/main/java/org/bcss/collect/naxa/sync/DownloadableItemLocalSource.java
Labels: low priority

#147 [#146] when project download is running, edu and form are queued
  collect_app/src/main/java/org/bcss/collect/naxa/educational/EducationalMaterialsRemoteSource.java
  collect_app/src/main/java/org/bcss/collect/naxa/notificationslist/FlaggedInstanceActivity.java
  collect_app/src/main/java/org/bcss/collect/naxa/onboarding/XMLFormDownloadService.java
Labels: bug

#149 [#148] removes view data button
  collect_app/src/main/java/org/bcss/collect/naxa/notificationslist/FlaggedInstanceActivity.java
Labels: bug, low priority

#161 [#160} adds instace id removes deviceId in submission params
  collect_app/src/main/java/org/bcss/collect/android/provider/InstanceProvider.java
  collect_app/src/main/java/org/bcss/collect/android/upload/InstanceServerUploader.java
  collect_app/src/main/java/org/odk/collect/android/dao/InstancesDao.java
Labels: enhancement
